from enum import Enum, IntEnum


class CallbackActions(str, Enum):
    """Callback actions"""

    ACCEPTED_CONSENT = "CONSENT_"
    REDIRECT_TO_MENU = "MENU"
    LEAVE_FEEDBACK = "LEAVE_FEEDBACK"
    HOTEL = "HOTEL"

    # Feedback callbacks
    FEEDBACK_ZONE = "_SPECIAL_ZONE_"
    FEEDBACK_RATE = "RATE"
    FEEDBACK_THUMB_UP = "THUMB_UP"
    FEEDBACK_THUMB_DOWN = "THUMB_DOWN"
    LAST_FEEDBACK = "LASTFEEDBACK"

    # Manager callbacks
    MGR_PROMPT_ZONE = "MGR_PROMPT_ZONE"
    MGR_EDIT_PROMPT = "MGR_EDIT_PROMPT"
    MGR_SAVE_PROMPT = "MGR_SAVE_PROMPT"
    MGR_RESET_PROMPT = "MGR_RESET_PROMPT"
    MGR_STATUS = "MGR_STATUS"
    MGR_QR_ZONE = "MGR_QR_ZONE"
    MGR_QR = "MGR_QR"
    MGR_REPORT_ALL = "MGR_REPORT_ALL"
    MGR_REPORT_PERIOD = "_MGR_REPORT_"
    MGR_REPORTS = "MGR_REPORTS"
    MGR_REPORT_HOTEL = "_MGR_REPORT_HOTEL_"
    MGR_NEGATIVE_FEEDBACKS_PAGE = "MGR_NEGATIVE_FEEDBACKS_PAGE"
    MGR_NEGATIVE_FEEDBACKS = "MGR_NEGATIVE_FEEDBACKS"
    MGR_FEEDBACK = "MGR_FEEDBACK"
    MGR_PROMPTS = "MGR_PROMPTS"

    # Admin callbacks
    ADMIN_USER_MANAGEMENT = "ADMIN_USER_MANAGEMENT"
    ADMIN_BRANCH_MANAGEMENT = "ADMIN_BRANCH_MANAGEMENT"
    ADMIN_SELECT_BRANCH = "ADMIN_SELECT_BRANCH"
    ADMIN_SELECT_BRANCH_PAGE = "ADMIN_SELECT_BRANCH_PAGE"
    ADMIN_SELECTED_BRANCH = "ADMIN_SELECTED_BRANCH"
    ADMIN_EDIT_HOTEL_NAME = "ADMIN_EDIT_HOTEL_NAME"
    ADMIN_EDIT_HOTEL_DESCRIPTION = "ADMIN_EDIT_HOTEL_DESCRIPTION"
    ADMIN_SELECT_ZONE = "ADMIN_SELECT_ZONE"
    ADMIN_SELECT_ZONE_PAGE = "ADMIN_SELECT_ZONE_PAGE"
    ADMIN_EDIT_ZONE = "ADMIN_EDIT_ZONE"
    ADMIN_EDIT_ZONE_NAME = "ADMIN_EDIT_ZONE_NAME"
    ADMIN_EDIT_ZONE_DESCRIPTION = "ADMIN_EDIT_ZONE_DESCRIPTION"
    ADMIN_EDIT_ZONE_ADULT = "ADMIN_EDIT_ZONE_ADULT"
    ADMIN_DELETE_ZONE = "ADMIN_DELETE_ZONE"
    ADMIN_ADD_ZONE = "ADMIN_ADD_ZONE"
    ADMIN_ADD_BRANCH = "ADMIN_ADD_BRANCH"
    ADMIN_ADD_USER = "ADMIN_ADD_USER"
    ADMIN_LIST_USERS = "ADMIN_LIST_USERS"
    ADMIN_SELECT_HOTEL = "ADMIN_SELECT_HOTEL"
    ADMIN_SELECT_ROLE = "ADMIN_SELECT_ROLE"
    ADMIN_SELECT_CHANNEL = "ADMIN_SELECT_CHANNEL"
    ADMIN_MAIN_MENU = "ADMIN_MAIN_MENU"
    ADMIN_HOTELS_LIST = "ADMIN_HOTELS_LIST"
    ADMIN_HOTELS_LIST_PAGE = "ADMIN_HOTELS_LIST_PAGE"
    ADMIN_HOTEL_USERS = "ADMIN_HOTEL_USERS"
    ADMIN_HOTEL_USERS_PAGE = "ADMIN_HOTEL_USERS_PAGE"
    ADMIN_USER_DETAIL = "ADMIN_USER_DETAIL"
    ADMIN_USER_DEACTIVATE = "ADMIN_USER_DEACTIVATE"
    ADMIN_USER_BACK_TO_LIST = "ADMIN_USER_BACK_TO_LIST"
    ADMIN_EDIT_USER = "ADMIN_EDIT_USER"
    ADMIN_EDIT_USER_HOTEL_STATUS = "ADMIN_EDIT_HOTEL"
    ADMIN_CHANGE_USER_ROLE = "ADMIN_CHANGE_USER_ROLE"
    ADMIN_TOGGLE_USER_STATUS = "ADMIN_TOGGLE_USER_STATUS"
    ADMIN_DELETE_USER = "ADMIN_DELETE_USER"
    ADMIN_CONFIRM_ROLE_CHANGE = "ADMIN_CONFIRM_ROLE_CHANGE"

    # Info callbacks
    ABOUT_BOT = "ABOUT_BOT"
    HELP = "HELP"

    def __str__(self):
        return self.value


class Priority(IntEnum):
    """Task priority levels (lower number = higher priority)"""

    HIGH = 1  # Relevance and sentiment analysis
    MEDIUM = 2  # Review analysis
    LOW = 3  # Other tasks
